<?php
/**
 * Valores por defecto del panel de configuracion (fuente: sql/2026_05_20_configuracion_general_plantilla.sql).
 */
function configuracion_plantilla_defaults(): array
{
    return [
        'tipo_codigo_barras_default' => 'QR',
        'id_tienda_default' => 1,
        'markup_pct_default' => '220.00',
        'descuento_general_mostrador' => '30.00',
        'descuento_insumos_mostrador' => '0.00',
        'mayoreo_umbral_mxn' => '6000.00',
        'mayoreo_descuento_pct' => '50.00',
        'id_forma_pago_default' => 0,
        'id_impuesto_default' => 0,
        'ticket_nombre_comercial' => 'Plateria el Angel',
        'ticket_leyenda_folio' => 'Folio',
        'ticket_horario' => 'Horario: 1:30 PM - 7:00 PM',
        'ticket_mensaje_pie' => 'Gracias por su preferencia',
        'ticket_ancho_columnas' => 42,
        'ticket_margen_izquierdo' => 60,
        'ticket_mostrar_impuesto' => true,
        'ticket_mostrar_empleado' => true,
        'impresion_habilitada' => true,
        'impresion_caja_token' => 'cambiar_token_seguro',
        'impresion_nombre_impresora' => 'EPSON TM-T20 Receipt',
        'impresion_id_tienda_caja' => 0,
        'etiqueta_impresion_habilitada' => true,
        'etiqueta_impresion_nombre_impresora' => 'Argox OS-2140 PPLA',
        'etiqueta_impresion_token' => '',
        'etiqueta_ancho_mm' => 60,
        'etiqueta_alto_mm' => 10,
        'etiqueta_gap_mm' => '3',
        'etiqueta_ala_mm' => 17,
        'etiqueta_media_mm' => 17,
        'etiqueta_cola_mm' => 26,
        'etiqueta_alto_cola_mm' => 5,
        'etiqueta_dpi' => 203,
        'etiqueta_offset_x' => 0,
        'etiqueta_offset_y' => 0,
        'etiqueta_lang' => 'IMAGEN',
        'etiqueta_img_shift_barcode_mm' => '4',
        'etiqueta_img_shift_precio_mm' => '6',
        'etiqueta_img_margen_izq_barcode_mm' => '2.5',
        'etiqueta_img_margen_der_barcode_mm' => '1',
        'etiqueta_img_gap_barcode_texto_mm' => '0.3',
        'etiqueta_img_margen_inferior_aux_mm' => '1.5',
        'etiqueta_img_alto_barcode_ratio' => '0.72',
        'etiqueta_img_tam_aux_pt' => 11,
        'etiqueta_img_tam_precio_pt' => 24,
        'etiqueta_img_precio_baseline_factor' => '0.30',
        'etiqueta_img_tam_variante_pt' => 8,
        'etiqueta_img_margen_inferior_variante_mm' => '1.2',
        'etiqueta_img_precio_con_variante_pt' => 20,
        'contrato_ciudad' => 'Celaya, Gto.',
        'contrato_domicilio_fuente_trabajo' => 'Andador Nicolas Bravo No. 104 Celaya, Gto.',
        'contrato_nombre_patron' => 'BEATRIZ MARTHA HERNANDEZ ALVARADO',
        'contrato_tribunal_ciudad' => 'Guanajuato, Guanajuato',
        'contrato_jornada_horas_semanales' => 48,
        'contrato_nacionalidad_default' => 'Mexicana',
        'spei_deposito_habilitado' => false,
        'spei_beneficiario' => '',
        'spei_banco' => '',
        'spei_clabe' => '',
        'spei_instrucciones' => '',
        'spei_referencia_prefijo' => 'VENTA',
    ];
}
