# -*- coding: utf-8 -*-
"""Correccion ortografica solo en textos visibles de vistas PHP."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REPLACEMENTS = [
    ("Cerrar sesion", "Cerrar sesión"),
    ("Inicia sesion", "Inicia sesión"),
    ("iniciar sesion", "iniciar sesión"),
    ("Plateria 0.925", "Platería 0.925"),
    ("Plateria el Angel", "Platería El Ángel"),
    ("Plateria El Angel", "Platería El Ángel"),
    ("acompaana", "acompaña"),
    ("acompaana", "acompaña"),
    ("Tu carrito esta vacio", "Tu carrito está vacío"),
    ("Explorar el catalogo", "Explorar el catálogo"),
    (">Catalogo<", ">Catálogo<"),
    ("podras recoger", "podrás recoger"),
    ("identificacion oficial", "identificación oficial"),
    ("numero de orden", "número de orden"),
    ("No realizamos envios", "No realizamos envíos"),
    ("debere presentar", "deberé presentar"),
    ("Sin permiso de lectura del modulo.", "Sin permiso de lectura del módulo."),
    ("entra a un modulo permitido.", "entra a un módulo permitido."),
    ("acceder a este modulo.", "acceder a este módulo."),
    ("Ir a modulo permitido", "Ir a módulo permitido"),
    ("No se encontro", "No se encontró"),
    ("el articulo.", "el artículo."),
    ("este articulo?", "este artículo?"),
    ("articulos de catalogo", "artículos de catálogo"),
    ("Articulo de Catalogo", "Artículo de catálogo"),
    ("Nuevo Articulo", "Nuevo artículo"),
    ("Editar Articulo de Catalogo", "Editar artículo de catálogo"),
    ("la notificacion.", "la notificación."),
    ("Centro de configuracion", "Centro de configuración"),
    ("Guardar configuracion", "Guardar configuración"),
    ("Secciones de configuracion", "Secciones de configuración"),
    ("Fecha de operacion", "Fecha de operación"),
    ("Fecha operacion", "Fecha operación"),
    ("<th>Descripcion</th>", "<th>Descripción</th>"),
    ("<th>Codigo</th>", "<th>Código</th>"),
    ("<th>Telefono</th>", "<th>Teléfono</th>"),
    ("<th>Direccion</th>", "<th>Dirección</th>"),
    ("<th>Credito</th>", "<th>Crédito</th>"),
    ("<th>Codigo pieza</th>", "<th>Código pieza</th>"),
    ("<th>Codigo en lista</th>", "<th>Código en lista</th>"),
    ("<option>Descripcion</option>", "<option>Descripción</option>"),
    ("Descripcion:", "Descripción:"),
    ("Informacion Personal", "Información personal"),
    ("Informacion Base", "Información base"),
    ("Configuracion Comercial", "Configuración comercial"),
    ("Credito a favor", "Crédito a favor"),
    ("El credito aplicado", "El crédito aplicado"),
    ("Aplicar credito", "Aplicar crédito"),
    ("Credito aplicado", "Crédito aplicado"),
    ("credito por cambio", "crédito por cambio"),
    ("credito por devolucion", "crédito por devolución"),
    ("Contrasena temporal", "Contraseña temporal"),
    ("Contrasena:", "Contraseña:"),
    ("Empleado en sesion", "Empleado en sesión"),
    ("Escanear con camara", "Escanear con cámara"),
    ("camara aqui", "cámara aquí"),
    ("escaner no esta", "escáner no está"),
    ("en esta pagina", "en esta página"),
    ("Vuelve a iniciar sesion", "Vuelve a iniciar sesión"),
    ("Publico general", "Público general"),
    ("sitio publico", "sitio público"),
    ("catalogo visible", "catálogo visible"),
    ("catalogo visitante", "catálogo visitante"),
    ("Modo de impresion", "Modo de impresión"),
    ("Modo de devolucion", "Modo de devolución"),
    ("Registrar devolucion", "Registrar devolución"),
    ("Devolucion registrada", "Devolución registrada"),
    ("devolucion de", "devolución de"),
    ("devolucion mostrador", "devolución mostrador"),
    ("Pantalla unica", "Pantalla única"),
    ("Tu usuario no esta vinculado", "Tu usuario no está vinculado"),
    ("La tarjeta esta deshabilitada", "La tarjeta está deshabilitada"),
    ("no esta autorizado", "no está autorizado"),
    ("aun no esta", "aún no está"),
    ("aun no nos", "aún no nos"),
    ("Aun no hay", "Aún no hay"),
    ("Aun no tienes", "Aún no tienes"),
    ("Aun no recibimos", "Aún no recibimos"),
    ("Numero de orden", "Número de orden"),
    ("Numero exterior", "Número exterior"),
    ("Numero interior", "Número interior"),
    ("El numero de tarjeta", "El número de tarjeta"),
    ("El codigo de seguridad", "El código de seguridad"),
    ("Codigo Mercado Pago", "Código Mercado Pago"),
    ("Codigo postal", "Código postal"),
    ("Codigo vacio", "Código vacío"),
    ("Codigo pieza actual", "Código pieza actual"),
    ("Codigo pieza nueva", "Código pieza nueva"),
    ("Codigo pieza *", "Código pieza *"),
    ("Codigo pieza", "Código pieza"),
    ("Codigo (barras", "Código (barras"),
    ("Codigo:", "Código:"),
    ("Codigo de barras. Plano", "Código de barras. Plano"),
    ("Telefono:", "Teléfono:"),
    ("Direccion (opcional)", "Dirección (opcional)"),
    ("direccion de contacto", "dirección de contacto"),
    ("direccion del proveedor", "dirección del proveedor"),
    ("registrar direccion", "registrar dirección"),
    ("Desea agregar direccion", "Desea agregar dirección"),
    ("Desea registrar direccion", "Desea registrar dirección"),
    ("Si, registrar direccion", "Sí, registrar dirección"),
    ("tiene direccion;", "tiene dirección;"),
    ("modulo de direcciones", "módulo de direcciones"),
    ("Tamano codigo", "Tamaño código"),
    ("Tamano precio", "Tamaño precio"),
    ("tamano de texto", "tamaño de texto"),
    ("dejar vacio", "dejar vacío"),
    ("Dejar vacio", "Dejar vacío"),
    ("vacio =", "vacío ="),
    ("vacio para", "vacío para"),
    ("Operacion y valores", "Operación y valores"),
    ("Metodo de calculo", "Método de cálculo"),
    ("calculo actual", "cálculo actual"),
    ("editen despues", "editen después"),
    ("despues en Punto", "después en Punto"),
    ("despues de la barra", "después de la barra"),
    ("cambiarla despues.", "cambiarla después."),
    ("Esta accion", "Esta acción"),
    ("enviado a impresion", "enviado a impresión"),
    ("Enviando ticket a impresion", "Enviando ticket a impresión"),
    ("cola de impresion", "cola de impresión"),
    ("envio directo", "envío directo"),
    ("captura e impresion.", "captura e impresión."),
    ("reimpresion", "reimpresión"),
    ("liquidacion de apartado", "liquidación de apartado"),
    ("no tiene lineas de detalle", "no tiene líneas de detalle"),
    ("precios de las lineas", "precios de las líneas"),
    ("<label>Lineas</label>", "<label>Líneas</label>"),
    ("- Selecciona linea -", "- Selecciona línea -"),
    ("Selecciona la linea", "Selecciona la línea"),
    ("elige la linea", "elige la línea"),
    ("la linea a sustituir", "la línea a sustituir"),
    ("la linea a reemplazar", "la línea a reemplazar"),
    ("Linea a reemplazar", "Línea a reemplazar"),
    ("Lineas:", "Líneas:"),
    ("desde aqui.", "desde aquí."),
    ("aparecen aqui.", "aparecen aquí."),
    ("Desde aqui", "Desde aquí"),
    ("alta un cliente aqui", "alta un cliente aquí"),
    ("constancia oficial del dia", "constancia oficial del día"),
    ("Sin telefono", "Sin teléfono"),
    ("Buscar por descripcion", "Buscar por descripción"),
    ("Buscar por nombre o descripcion", "Buscar por nombre o descripción"),
    ("Buscar por nombre, correo, telefono o direccion", "Buscar por nombre, correo, teléfono o dirección"),
    ("Buscar por nombre, correo, telefono o proveedor", "Buscar por nombre, correo, teléfono o proveedor"),
    ("Buscar por nombre, contacto o telefono", "Buscar por nombre, contacto o teléfono"),
    ("Ingrese descripcion", "Ingrese descripción"),
    ("Lee la descripcion", "Lee la descripción"),
    ("cada opcion", "cada opción"),
    ("Jerarquia de direccion", "Jerarquía de dirección"),
    ("busqueda y alta en linea", "búsqueda y alta en línea"),
    ("catalogos al escribir", "catálogos al escribir"),
    ("- Primero en catalogo -", "- Primero en catálogo -"),
    ("Codigo de barras en piezas", "Código de barras en piezas"),
    ("Usa el numero", "Usa el número"),
    ("cantidad maxima por operacion", "cantidad máxima por operación"),
    ("Si esta vacio", "Si está vacío"),
    ("Cliente y codigo son", "Cliente y código son"),
    ("escribe codigo y", "escribe código y"),
    ("escanea un codigo.", "escanea un código."),
    ("Escribe o escanea un codigo.", "Escribe o escanea un código."),
    ("opcional si usas codigo", "opcional si usas código"),
    ("Indica el codigo", "Indica el código"),
    ("Indica un codigo", "Indica un código"),
    ("Indica ID de apartado o codigo", "Indica ID de apartado o código"),
    ("codigo ya esta", "código ya está"),
    ("codigo de la pieza", "código de la pieza"),
    ("Ingresa un codigo", "Ingresa un código"),
    ("Escanea o escribe el codigo", "Escanea o escribe el código"),
    ("<strong>Categoria:</strong>", "<strong>Categoría:</strong>"),
    (">Categoria:</label>", ">Categoría:</label>"),
    ("Rotar piezas del catalogo", "Rotar piezas del catálogo"),
    (" · Codigo: ", " · Código: "),
    ('related-col">Descripcion</th>', 'related-col">Descripción</th>'),
    ('name-col">Descripcion</th>', 'name-col">Descripción</th>'),
    ("encolado para impresion.", "encolado para impresión."),
    ("Escaner aun no", "Escáner aún no"),
    ("Camara no disponible", "Cámara no disponible"),
    ("Abre esta pagina", "Abre esta página"),
    ("en tu telefono.", "en tu teléfono."),
    ("Para pagar con credito a favor", "Para pagar con crédito a favor"),
    ("no tiene credito disponible", "no tiene crédito disponible"),
    ("confirmacion. Revisa", "confirmación. Revisa"),
    ("mas tarde.", "más tarde."),
    ("compras en linea.", "compras en línea."),
    ("Parametros del arqueo", "Parámetros del arqueo"),
    ("No leida", "No leída"),
    (">Leida<", ">Leída<"),
    ("Nueva Notificacion", "Nueva Notificación"),
    ("Editar Notificacion", "Editar Notificación"),
    ("escribe codigo y", "escribe código y"),
    (" · Codigo: ", " · Código: "),
]

# Ordenar por longitud descendente para evitar reemplazos parciales encadenados
REPLACEMENTS = sorted(set(REPLACEMENTS), key=lambda x: len(x[0]), reverse=True)


def collect_files():
    files = []
    for rel in ("admin/views", "user", "includes"):
        base = ROOT / rel
        if base.exists():
            files.extend(base.rglob("*.php"))
    for name in ("index.php", "catalogo.php"):
        p = ROOT / name
        if p.exists():
            files.append(p)
    return files


def main():
    changed = 0
    for path in collect_files():
        text = path.read_text(encoding="utf-8")
        orig = text
        for old, new in REPLACEMENTS:
            text = text.replace(old, new)
        if text != orig:
            if "<?rhr" in text or "<?oho" in text:
                raise SystemExit(f"Posible corrupcion en {path}")
            path.write_text(text, encoding="utf-8")
            changed += 1
    print(f"OK: {changed} archivos")


if __name__ == "__main__":
    main()
